export interface DefaultCategoryDefinition {
  name: string;
  subcategories: string[];
}

export const DEFAULT_INCOME_CATEGORIES: DefaultCategoryDefinition[] = [
  {
    name: "Salary",
    subcategories: ["Base Pay", "Bonus", "Allowances", "Reimbursements"],
  },
  {
    name: "Investment Income",
    subcategories: ["Capital Gains", "Dividends", "Interest", "RESP Grant"],
  },
  {
    name: "Other Income",
    subcategories: [
      "Blogging",
      "Business Reimbursement",
      "Cashback",
      "Consulting",
      "Credit Card Reward",
      "Employee Stock Option",
      "Gifts Received",
      "Income Tax Refund",
      "Rental Income",
      "State & Local Tax Refund",
      "Transfer Bonus",
      "Tutoring",
    ],
  },
  {
    name: "Retirement Income",
    subcategories: ["CPP/QPP Benefits", "Pension", "EPF / NPS Withdrawal"],
  },
  {
    name: "Wages & Salary",
    subcategories: [
      "Bonus",
      "Commission",
      "Employer Matching",
      "Gross Pay",
      "Net Pay",
      "Overtime",
      "Vacation Pay",
    ],
  },
];

export const DEFAULT_EXPENSE_CATEGORIES: DefaultCategoryDefinition[] = [
  {
    name: "SIP & Mutual Funds",
    subcategories: [
      "Equity SIP",
      "ELSS Tax Saver",
      "Debt Fund",
      "Index Fund",
      "Lumpsum Investment",
    ],
  },
  {
    name: "Stocks & Equities",
    subcategories: ["NSE Equity", "BSE Equity", "US Equities", "IPO Allotment"],
  },
  {
    name: "Gold & Fixed Deposits",
    subcategories: [
      "Sovereign Gold Bond (SGB)",
      "Bank FD",
      "PPF / EPF",
      "Digital Gold",
    ],
  },
  {
    name: "Rent",
    subcategories: ["House Rent", "Society Maintenance", "Security Deposit"],
  },
  {
    name: "Groceries",
    subcategories: [
      "Supermarket & DMart",
      "Blinkit / Zepto / InstaMart",
      "BigBasket",
      "Vegetables & Milk",
    ],
  },
  {
    name: "Utilities",
    subcategories: [
      "Electricity Bill",
      "Water Bill",
      "Broadband Internet",
      "Mobile Recharge",
      "LPG Cylinder",
    ],
  },
  {
    name: "Dining Out",
    subcategories: [
      "Swiggy & Zomato",
      "Restaurants & Dining",
      "Cafes & Coffee",
      "Office Canteen",
    ],
  },
  {
    name: "Fuel & Transit",
    subcategories: [
      "Petrol & Diesel",
      "Cab (Uber / Ola)",
      "Metro & Train",
      "Toll & Fastag",
    ],
  },
  {
    name: "Medical & Health",
    subcategories: [
      "Medicines & Pharmacy",
      "Doctor & Hospital",
      "Health Insurance Premium",
      "Lab Tests",
    ],
  },
  {
    name: "Credit Card Payment",
    subcategories: ["Statement Settlement", "EMI Payment", "Annual Fee"],
  },
  {
    name: "Automobile",
    subcategories: [
      "Accessories",
      "Car Payment",
      "Cleaning",
      "Fines",
      "Gasoline",
      "Licencing",
      "Maintenance",
      "Parking",
      "Parts",
      "Toll Charges",
    ],
  },
  {
    name: "Bank Fees",
    subcategories: ["ATM", "Annual", "NSF", "Other", "Overdraft", "Service"],
  },
  {
    name: "Bills",
    subcategories: [
      "Accounting",
      "Cable TV",
      "Cell Phone",
      "Electricity",
      "Internet",
      "Lawyer",
      "Natural Gas",
      "Satellite Radio",
      "Streaming",
      "Telephone",
      "Water & Sewer",
      "Water Heater",
    ],
  },
  {
    name: "Business",
    subcategories: [
      "Airfare",
      "Alcohol",
      "Bank Fees",
      "Car Rental",
      "Cell Phone",
      "Computer Hardware",
      "Computer Software",
      "Dining Out",
      "Education",
      "Gasoline",
      "Internet",
      "Lodging",
      "Mileage",
      "Miscellaneous",
      "Parking",
      "Recreation",
      "Toll Charges",
      "Transit",
    ],
  },
  {
    name: "Cash Withdrawal",
    subcategories: [
      "Barbadian Dollars",
      "Bermudian Dollars",
      "Canadian Dollars",
      "Costa Rican Colones",
      "Croatian Kunas",
      "Dominican Republic Pesos",
      "Eastern Caribbean Dollars",
      "Euros",
      "Forints",
      "Honduran Lempiras",
      "Hong Kong Dollars",
      "Indonesian Rupiah",
      "Malaysian Ringgits",
      "Mexican Pesos",
      "Peruvian Soles",
      "Singapore Dollars",
      "Thai Baht",
      "US Dollars",
    ],
  },
  { name: "Charitable Donations", subcategories: [] },
  {
    name: "Childcare",
    subcategories: [
      "Activities",
      "Allowance",
      "Babysitting",
      "Books",
      "Clothing",
      "Counselling",
      "Daycare",
      "Entertainment",
      "Fees",
      "Furnishings",
      "Gifts",
      "Haircut",
      "Medication",
      "Shoes",
      "Sporting Goods",
      "Sports",
      "Supplies",
      "Toiletries",
      "Toys & Games",
    ],
  },
  {
    name: "Clothing",
    subcategories: ["Accessories", "Clothes", "Coats", "Shoes"],
  },
  {
    name: "Computer",
    subcategories: ["Hardware", "Software", "Web Hosting"],
  },
  {
    name: "Education",
    subcategories: ["Books", "Fees", "Tuition"],
  },
  {
    name: "Food",
    subcategories: ["Alcohol", "Cannabis", "Dining Out", "Groceries"],
  },
  {
    name: "Furnishings",
    subcategories: [
      "Accessories",
      "Appliances",
      "Basement",
      "Bathroom",
      "Bedroom",
      "Dining Room",
      "Dishes",
      "Kitchen",
      "Living Room",
      "Office",
      "Outdoor",
      "Plants",
    ],
  },
  {
    name: "Gifts",
    subcategories: [
      "Anniversary",
      "Birthday",
      "Cards",
      "Christmas",
      "Flowers",
      "Mother's Day",
      "RESP Contribution",
      "Valentines",
      "Wedding",
    ],
  },
  {
    name: "Healthcare",
    subcategories: [
      "Counselling",
      "Dental",
      "Eyecare",
      "Fertility",
      "Fitness",
      "Hospital",
      "Massage",
      "Medication",
      "Physician",
      "Physiotherapy",
      "Prescriptions",
      "Supplies",
    ],
  },
  {
    name: "Housing",
    subcategories: [
      "Fees",
      "Garden Supplies",
      "Home Improvement",
      "Maintenance",
      "Mortgage Interest",
      "Mortgage Principal",
      "Rent",
      "Supplies",
      "Tools",
    ],
  },
  {
    name: "Insurance",
    subcategories: [
      "Automobile",
      "Disability",
      "Health",
      "Homeowner/Renter",
      "Life",
      "Travel",
    ],
  },
  { name: "Interest Expense", subcategories: [] },
  {
    name: "Leisure",
    subcategories: [
      "Books & Magazines",
      "CD",
      "Camera/Film",
      "Camping",
      "Cover Charge",
      "Cultural Events",
      "DVD",
      "Electronics",
      "Entertaining",
      "Entertainment",
      "Fees",
      "Gambling",
      "LPs",
      "Movies",
      "Newspaper",
      "Sporting Events",
      "Sporting Goods",
      "Sports",
      "Toys & Games",
      "Transit",
      "VHS",
      "Video Rentals",
    ],
  },
  { name: "Licencing Fees", subcategories: [] },
  {
    name: "Loan",
    subcategories: ["Loan Interest", "Loan Principal", "Mortgage Interest"],
  },
  {
    name: "Miscellaneous",
    subcategories: ["Postage", "Postcards", "Tools", "Transit"],
  },
  {
    name: "Personal Care",
    subcategories: [
      "Dry Cleaning",
      "Haircut",
      "Laundry",
      "Pedicure",
      "Toiletries",
    ],
  },
  {
    name: "Pet Care",
    subcategories: ["Food", "Supplies", "Veterinarian"],
  },
  {
    name: "Taxes",
    subcategories: [
      "CPP/QPP Contributions",
      "EI Premiums",
      "Federal Income",
      "Goods & Services",
      "Other",
      "Property",
      "Real Estate",
      "State/Provincial",
      "Union Dues",
    ],
  },
  {
    name: "Vacation",
    subcategories: [
      "Airfare",
      "Car Rental",
      "Entertainment",
      "Gasoline",
      "Lodging",
      "Miscellaneous",
      "Parking",
      "Transit",
      "Travel",
    ],
  },
];
